[platformio]
description = Firmware OBD-II independente para JC3248W535EN
default_envs = obd-jc3248w535
boards_dir = boards
src_dir = src
lib_dir = lib

[env:obd-jc3248w535]
platform = espressif32@6.6.0
board = 320x480
framework = espidf
build_type = debug
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = lvgl/lvgl@8.3.11
build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
    -D LV_CONF_INCLUDE_SIMPLE
    -D OBD_SIMULATION=0
    -Isrc
    -Isrc/drivers
    -Isrc/ui
    -Isrc/obd
    -Isrc/ble
    -Isrc/settings
    -Isrc/screens
    -Wno-error=format-truncation

